language: python

python: "3.6"

dist: trusty
sudo: required

matrix:
    fast_finish: true

cache: pip

services:
  mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE pf DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;'

install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - sed "s/mysql:\/\/test:test123@/mysql:\/\/root:@/" config.example.py > config.py
    - python create_db.py

script:
    - python -m pytest

notifications:
    email: false
