"""empty message

Revision ID: 82e57a6924a7
Revises: 
Create Date: 2017-07-16 22:16:46.533098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82e57a6924a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('games', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'level',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARBINARY(length=255),
               nullable=False)
    op.alter_column('users', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARBINARY(length=255),
               nullable=True)
    op.alter_column('users', 'level',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'created_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('games', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
