"""empty message

Revision ID: d48817b3982c
Revises: 82e57a6924a7
Create Date: 2017-07-18 09:28:06.689078

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd48817b3982c'
down_revision = '82e57a6924a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_prices',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.add_column('companies', sa.Column('website', sqlalchemy_utils.types.url.URLType(), nullable=True))
    op.add_column('game_info', sa.Column('website', sqlalchemy_utils.types.url.URLType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_info', 'website')
    op.drop_column('companies', 'website')
    op.drop_table('game_prices')
    # ### end Alembic commands ###
